services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: service-contract-system
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: service-contract-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${DB_CONNECTION}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"

volumes:
  mysql_data:
    